database:
  host: localhost
  port: "5432"
  user: trashscanner
  password: trashscanner
  name: trashscanner_db
  migrations_path: internal/database/migrations
  sslmode: disable
filestore:
  endpoint: localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  bucket: trashscanner-images
  use_ssl: false
auth_manager:
  access_token_ttl: 15m
  refresh_token_ttl: 168h
  signing_algorithm: EdDSA
predictor:
  address: http://localhost:8000
  token: secret-token
  max_predictions_in_processing: 10
server:
  host: localhost
  port: "8080"
log:
  level: debug 
  format: text
  file: ""
