database:
  host: localhost
  port: "5432"
  user: testuser
  password: testpassword
  name: testdb
  migrations_path: file://internal/database/migrations
  sslmode: disable
auth_manager:
  access_token_ttl: 15m
  refresh_token_ttl: 168h
  signing_algorithm: EdDSA
filestore:
  endpoint: localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  bucket: trashscanner-images
  use_ssl: false
predictor:
  address: http://10.10.10.10:8000
  token: token
  max_predictions_in_processing: 10